version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - ./docker-persist/db/pgsql:/var/lib/postgresql/data 
    networks:
      - postgres_network
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "7500:80"
    depends_on:
      - postgres
    networks:
      - postgres_network

networks: 
  postgres_network:
    driver: bridge
